/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SimRouteImport } from './routes/sim'
import { Route as ReurbRouteImport } from './routes/reurb'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PainelAdminRouteImport } from './routes/painel-admin'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostRouteImport } from './routes/host'
import { Route as GisRouteImport } from './routes/gis'
import { Route as FiscalizacaoRouteImport } from './routes/fiscalizacao'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ConsultaPublicaRouteImport } from './routes/consulta-publica'
import { Route as ConcluirCadastroRouteImport } from './routes/concluir-cadastro'
import { Route as AterRouteImport } from './routes/ater'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequerimentosIndexRouteImport } from './routes/requerimentos.index'
import { Route as EmpresasIndexRouteImport } from './routes/empresas.index'
import { Route as EmpreendimentosIndexRouteImport } from './routes/empreendimentos.index'
import { Route as DenunciasIndexRouteImport } from './routes/denuncias.index'
import { Route as VTokenRouteImport } from './routes/v.$token'
import { Route as RequerimentosNovoRouteImport } from './routes/requerimentos.novo'
import { Route as RequerimentosIdRouteImport } from './routes/requerimentos.$id'
import { Route as HostModulosRouteImport } from './routes/host.modulos'
import { Route as HostApiDocsRouteImport } from './routes/host.api-docs'
import { Route as EmpresasNovaRouteImport } from './routes/empresas.nova'
import { Route as EmpreendimentosNovoRouteImport } from './routes/empreendimentos.novo'
import { Route as EmpreendimentosMapaRouteImport } from './routes/empreendimentos.mapa'
import { Route as DocumentosEmitidosRouteImport } from './routes/documentos.emitidos'
import { Route as DenunciasNovaRouteImport } from './routes/denuncias.nova'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTiposRequerimentoRouteImport } from './routes/admin.tipos-requerimento'
import { Route as AdminPdfTemplatesRouteImport } from './routes/admin.pdf-templates'
import { Route as AdminPapelRouteImport } from './routes/admin.papel'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminCepramRouteImport } from './routes/admin.cepram'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminApiTokensRouteImport } from './routes/admin.api-tokens'
import { Route as RequerimentosIdEditarRouteImport } from './routes/requerimentos.$id.editar'
import { Route as EmpresasIdEditarRouteImport } from './routes/empresas.$id.editar'
import { Route as EmpreendimentosIdEditarRouteImport } from './routes/empreendimentos.$id.editar'
import { Route as DenunciasIdEditarRouteImport } from './routes/denuncias.$id.editar'
import { Route as AdminUsuariosNovoRouteImport } from './routes/admin.usuarios.novo'
import { Route as ApiPublicV1RequerimentosRouteImport } from './routes/api/public/v1/requerimentos'
import { Route as ApiPublicV1OpenapiRouteImport } from './routes/api/public/v1/openapi'
import { Route as ApiPublicV1EmpresasRouteImport } from './routes/api/public/v1/empresas'
import { Route as ApiPublicV1EmpreendimentosRouteImport } from './routes/api/public/v1/empreendimentos'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimRoute = SimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => rootRouteImport,
} as any)
const ReurbRoute = ReurbRouteImport.update({
  id: '/reurb',
  path: '/reurb',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAdminRoute = PainelAdminRouteImport.update({
  id: '/painel-admin',
  path: '/painel-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalizacaoRoute = FiscalizacaoRouteImport.update({
  id: '/fiscalizacao',
  path: '/fiscalizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaPublicaRoute = ConsultaPublicaRouteImport.update({
  id: '/consulta-publica',
  path: '/consulta-publica',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcluirCadastroRoute = ConcluirCadastroRouteImport.update({
  id: '/concluir-cadastro',
  path: '/concluir-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AterRoute = AterRouteImport.update({
  id: '/ater',
  path: '/ater',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequerimentosIndexRoute = RequerimentosIndexRouteImport.update({
  id: '/requerimentos/',
  path: '/requerimentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIndexRoute = EmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosIndexRoute = EmpreendimentosIndexRouteImport.update({
  id: '/empreendimentos/',
  path: '/empreendimentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciasIndexRoute = DenunciasIndexRouteImport.update({
  id: '/denuncias/',
  path: '/denuncias/',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RequerimentosNovoRoute = RequerimentosNovoRouteImport.update({
  id: '/requerimentos/novo',
  path: '/requerimentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const RequerimentosIdRoute = RequerimentosIdRouteImport.update({
  id: '/requerimentos/$id',
  path: '/requerimentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostModulosRoute = HostModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => HostRoute,
} as any)
const HostApiDocsRoute = HostApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => HostRoute,
} as any)
const EmpresasNovaRoute = EmpresasNovaRouteImport.update({
  id: '/empresas/nova',
  path: '/empresas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosNovoRoute = EmpreendimentosNovoRouteImport.update({
  id: '/empreendimentos/novo',
  path: '/empreendimentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosMapaRoute = EmpreendimentosMapaRouteImport.update({
  id: '/empreendimentos/mapa',
  path: '/empreendimentos/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosEmitidosRoute = DocumentosEmitidosRouteImport.update({
  id: '/emitidos',
  path: '/emitidos',
  getParentRoute: () => DocumentosRoute,
} as any)
const DenunciasNovaRoute = DenunciasNovaRouteImport.update({
  id: '/denuncias/nova',
  path: '/denuncias/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTiposRequerimentoRoute = AdminTiposRequerimentoRouteImport.update({
  id: '/admin/tipos-requerimento',
  path: '/admin/tipos-requerimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPdfTemplatesRoute = AdminPdfTemplatesRouteImport.update({
  id: '/admin/pdf-templates',
  path: '/admin/pdf-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPapelRoute = AdminPapelRouteImport.update({
  id: '/admin/papel',
  path: '/admin/papel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/admin/onboarding',
  path: '/admin/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/admin/home',
  path: '/admin/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCepramRoute = AdminCepramRouteImport.update({
  id: '/admin/cepram',
  path: '/admin/cepram',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiTokensRoute = AdminApiTokensRouteImport.update({
  id: '/admin/api-tokens',
  path: '/admin/api-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const RequerimentosIdEditarRoute = RequerimentosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => RequerimentosIdRoute,
} as any)
const EmpresasIdEditarRoute = EmpresasIdEditarRouteImport.update({
  id: '/empresas/$id/editar',
  path: '/empresas/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosIdEditarRoute = EmpreendimentosIdEditarRouteImport.update({
  id: '/empreendimentos/$id/editar',
  path: '/empreendimentos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciasIdEditarRoute = DenunciasIdEditarRouteImport.update({
  id: '/denuncias/$id/editar',
  path: '/denuncias/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosNovoRoute = AdminUsuariosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminUsuariosRoute,
} as any)
const ApiPublicV1RequerimentosRoute =
  ApiPublicV1RequerimentosRouteImport.update({
    id: '/api/public/v1/requerimentos',
    path: '/api/public/v1/requerimentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OpenapiRoute = ApiPublicV1OpenapiRouteImport.update({
  id: '/api/public/v1/openapi',
  path: '/api/public/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1EmpresasRoute = ApiPublicV1EmpresasRouteImport.update({
  id: '/api/public/v1/empresas',
  path: '/api/public/v1/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1EmpreendimentosRoute =
  ApiPublicV1EmpreendimentosRouteImport.update({
    id: '/api/public/v1/empreendimentos',
    path: '/api/public/v1/empreendimentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ater': typeof AterRoute
  '/concluir-cadastro': typeof ConcluirCadastroRoute
  '/consulta-publica': typeof ConsultaPublicaRoute
  '/documentos': typeof DocumentosRouteWithChildren
  '/fiscalizacao': typeof FiscalizacaoRoute
  '/gis': typeof GisRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel-admin': typeof PainelAdminRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reurb': typeof ReurbRoute
  '/sim': typeof SimRoute
  '/termos': typeof TermosRoute
  '/admin/api-tokens': typeof AdminApiTokensRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cepram': typeof AdminCepramRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/papel': typeof AdminPapelRoute
  '/admin/pdf-templates': typeof AdminPdfTemplatesRoute
  '/admin/tipos-requerimento': typeof AdminTiposRequerimentoRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/denuncias/nova': typeof DenunciasNovaRoute
  '/documentos/emitidos': typeof DocumentosEmitidosRoute
  '/empreendimentos/mapa': typeof EmpreendimentosMapaRoute
  '/empreendimentos/novo': typeof EmpreendimentosNovoRoute
  '/empresas/nova': typeof EmpresasNovaRoute
  '/host/api-docs': typeof HostApiDocsRoute
  '/host/modulos': typeof HostModulosRoute
  '/requerimentos/$id': typeof RequerimentosIdRouteWithChildren
  '/requerimentos/novo': typeof RequerimentosNovoRoute
  '/v/$token': typeof VTokenRoute
  '/denuncias/': typeof DenunciasIndexRoute
  '/empreendimentos/': typeof EmpreendimentosIndexRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/requerimentos/': typeof RequerimentosIndexRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/denuncias/$id/editar': typeof DenunciasIdEditarRoute
  '/empreendimentos/$id/editar': typeof EmpreendimentosIdEditarRoute
  '/empresas/$id/editar': typeof EmpresasIdEditarRoute
  '/requerimentos/$id/editar': typeof RequerimentosIdEditarRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/empreendimentos': typeof ApiPublicV1EmpreendimentosRoute
  '/api/public/v1/empresas': typeof ApiPublicV1EmpresasRoute
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/requerimentos': typeof ApiPublicV1RequerimentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ater': typeof AterRoute
  '/concluir-cadastro': typeof ConcluirCadastroRoute
  '/consulta-publica': typeof ConsultaPublicaRoute
  '/documentos': typeof DocumentosRouteWithChildren
  '/fiscalizacao': typeof FiscalizacaoRoute
  '/gis': typeof GisRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel-admin': typeof PainelAdminRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reurb': typeof ReurbRoute
  '/sim': typeof SimRoute
  '/termos': typeof TermosRoute
  '/admin/api-tokens': typeof AdminApiTokensRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cepram': typeof AdminCepramRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/papel': typeof AdminPapelRoute
  '/admin/pdf-templates': typeof AdminPdfTemplatesRoute
  '/admin/tipos-requerimento': typeof AdminTiposRequerimentoRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/denuncias/nova': typeof DenunciasNovaRoute
  '/documentos/emitidos': typeof DocumentosEmitidosRoute
  '/empreendimentos/mapa': typeof EmpreendimentosMapaRoute
  '/empreendimentos/novo': typeof EmpreendimentosNovoRoute
  '/empresas/nova': typeof EmpresasNovaRoute
  '/host/api-docs': typeof HostApiDocsRoute
  '/host/modulos': typeof HostModulosRoute
  '/requerimentos/$id': typeof RequerimentosIdRouteWithChildren
  '/requerimentos/novo': typeof RequerimentosNovoRoute
  '/v/$token': typeof VTokenRoute
  '/denuncias': typeof DenunciasIndexRoute
  '/empreendimentos': typeof EmpreendimentosIndexRoute
  '/empresas': typeof EmpresasIndexRoute
  '/requerimentos': typeof RequerimentosIndexRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/denuncias/$id/editar': typeof DenunciasIdEditarRoute
  '/empreendimentos/$id/editar': typeof EmpreendimentosIdEditarRoute
  '/empresas/$id/editar': typeof EmpresasIdEditarRoute
  '/requerimentos/$id/editar': typeof RequerimentosIdEditarRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/empreendimentos': typeof ApiPublicV1EmpreendimentosRoute
  '/api/public/v1/empresas': typeof ApiPublicV1EmpresasRoute
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/requerimentos': typeof ApiPublicV1RequerimentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ater': typeof AterRoute
  '/concluir-cadastro': typeof ConcluirCadastroRoute
  '/consulta-publica': typeof ConsultaPublicaRoute
  '/documentos': typeof DocumentosRouteWithChildren
  '/fiscalizacao': typeof FiscalizacaoRoute
  '/gis': typeof GisRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/painel-admin': typeof PainelAdminRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reurb': typeof ReurbRoute
  '/sim': typeof SimRoute
  '/termos': typeof TermosRoute
  '/admin/api-tokens': typeof AdminApiTokensRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cepram': typeof AdminCepramRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/papel': typeof AdminPapelRoute
  '/admin/pdf-templates': typeof AdminPdfTemplatesRoute
  '/admin/tipos-requerimento': typeof AdminTiposRequerimentoRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/denuncias/nova': typeof DenunciasNovaRoute
  '/documentos/emitidos': typeof DocumentosEmitidosRoute
  '/empreendimentos/mapa': typeof EmpreendimentosMapaRoute
  '/empreendimentos/novo': typeof EmpreendimentosNovoRoute
  '/empresas/nova': typeof EmpresasNovaRoute
  '/host/api-docs': typeof HostApiDocsRoute
  '/host/modulos': typeof HostModulosRoute
  '/requerimentos/$id': typeof RequerimentosIdRouteWithChildren
  '/requerimentos/novo': typeof RequerimentosNovoRoute
  '/v/$token': typeof VTokenRoute
  '/denuncias/': typeof DenunciasIndexRoute
  '/empreendimentos/': typeof EmpreendimentosIndexRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/requerimentos/': typeof RequerimentosIndexRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/denuncias/$id/editar': typeof DenunciasIdEditarRoute
  '/empreendimentos/$id/editar': typeof EmpreendimentosIdEditarRoute
  '/empresas/$id/editar': typeof EmpresasIdEditarRoute
  '/requerimentos/$id/editar': typeof RequerimentosIdEditarRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/empreendimentos': typeof ApiPublicV1EmpreendimentosRoute
  '/api/public/v1/empresas': typeof ApiPublicV1EmpresasRoute
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/requerimentos': typeof ApiPublicV1RequerimentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ater'
    | '/concluir-cadastro'
    | '/consulta-publica'
    | '/documentos'
    | '/fiscalizacao'
    | '/gis'
    | '/host'
    | '/login'
    | '/notificacoes'
    | '/painel-admin'
    | '/perfil'
    | '/privacidade'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/reurb'
    | '/sim'
    | '/termos'
    | '/admin/api-tokens'
    | '/admin/auditoria'
    | '/admin/cepram'
    | '/admin/home'
    | '/admin/onboarding'
    | '/admin/papel'
    | '/admin/pdf-templates'
    | '/admin/tipos-requerimento'
    | '/admin/usuarios'
    | '/denuncias/nova'
    | '/documentos/emitidos'
    | '/empreendimentos/mapa'
    | '/empreendimentos/novo'
    | '/empresas/nova'
    | '/host/api-docs'
    | '/host/modulos'
    | '/requerimentos/$id'
    | '/requerimentos/novo'
    | '/v/$token'
    | '/denuncias/'
    | '/empreendimentos/'
    | '/empresas/'
    | '/requerimentos/'
    | '/admin/usuarios/novo'
    | '/denuncias/$id/editar'
    | '/empreendimentos/$id/editar'
    | '/empresas/$id/editar'
    | '/requerimentos/$id/editar'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/empreendimentos'
    | '/api/public/v1/empresas'
    | '/api/public/v1/openapi'
    | '/api/public/v1/requerimentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ater'
    | '/concluir-cadastro'
    | '/consulta-publica'
    | '/documentos'
    | '/fiscalizacao'
    | '/gis'
    | '/host'
    | '/login'
    | '/notificacoes'
    | '/painel-admin'
    | '/perfil'
    | '/privacidade'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/reurb'
    | '/sim'
    | '/termos'
    | '/admin/api-tokens'
    | '/admin/auditoria'
    | '/admin/cepram'
    | '/admin/home'
    | '/admin/onboarding'
    | '/admin/papel'
    | '/admin/pdf-templates'
    | '/admin/tipos-requerimento'
    | '/admin/usuarios'
    | '/denuncias/nova'
    | '/documentos/emitidos'
    | '/empreendimentos/mapa'
    | '/empreendimentos/novo'
    | '/empresas/nova'
    | '/host/api-docs'
    | '/host/modulos'
    | '/requerimentos/$id'
    | '/requerimentos/novo'
    | '/v/$token'
    | '/denuncias'
    | '/empreendimentos'
    | '/empresas'
    | '/requerimentos'
    | '/admin/usuarios/novo'
    | '/denuncias/$id/editar'
    | '/empreendimentos/$id/editar'
    | '/empresas/$id/editar'
    | '/requerimentos/$id/editar'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/empreendimentos'
    | '/api/public/v1/empresas'
    | '/api/public/v1/openapi'
    | '/api/public/v1/requerimentos'
  id:
    | '__root__'
    | '/'
    | '/ater'
    | '/concluir-cadastro'
    | '/consulta-publica'
    | '/documentos'
    | '/fiscalizacao'
    | '/gis'
    | '/host'
    | '/login'
    | '/notificacoes'
    | '/painel-admin'
    | '/perfil'
    | '/privacidade'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/reurb'
    | '/sim'
    | '/termos'
    | '/admin/api-tokens'
    | '/admin/auditoria'
    | '/admin/cepram'
    | '/admin/home'
    | '/admin/onboarding'
    | '/admin/papel'
    | '/admin/pdf-templates'
    | '/admin/tipos-requerimento'
    | '/admin/usuarios'
    | '/denuncias/nova'
    | '/documentos/emitidos'
    | '/empreendimentos/mapa'
    | '/empreendimentos/novo'
    | '/empresas/nova'
    | '/host/api-docs'
    | '/host/modulos'
    | '/requerimentos/$id'
    | '/requerimentos/novo'
    | '/v/$token'
    | '/denuncias/'
    | '/empreendimentos/'
    | '/empresas/'
    | '/requerimentos/'
    | '/admin/usuarios/novo'
    | '/denuncias/$id/editar'
    | '/empreendimentos/$id/editar'
    | '/empresas/$id/editar'
    | '/requerimentos/$id/editar'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/empreendimentos'
    | '/api/public/v1/empresas'
    | '/api/public/v1/openapi'
    | '/api/public/v1/requerimentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AterRoute: typeof AterRoute
  ConcluirCadastroRoute: typeof ConcluirCadastroRoute
  ConsultaPublicaRoute: typeof ConsultaPublicaRoute
  DocumentosRoute: typeof DocumentosRouteWithChildren
  FiscalizacaoRoute: typeof FiscalizacaoRoute
  GisRoute: typeof GisRoute
  HostRoute: typeof HostRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PainelAdminRoute: typeof PainelAdminRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReurbRoute: typeof ReurbRoute
  SimRoute: typeof SimRoute
  TermosRoute: typeof TermosRoute
  AdminApiTokensRoute: typeof AdminApiTokensRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCepramRoute: typeof AdminCepramRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPapelRoute: typeof AdminPapelRoute
  AdminPdfTemplatesRoute: typeof AdminPdfTemplatesRoute
  AdminTiposRequerimentoRoute: typeof AdminTiposRequerimentoRoute
  AdminUsuariosRoute: typeof AdminUsuariosRouteWithChildren
  DenunciasNovaRoute: typeof DenunciasNovaRoute
  EmpreendimentosMapaRoute: typeof EmpreendimentosMapaRoute
  EmpreendimentosNovoRoute: typeof EmpreendimentosNovoRoute
  EmpresasNovaRoute: typeof EmpresasNovaRoute
  RequerimentosIdRoute: typeof RequerimentosIdRouteWithChildren
  RequerimentosNovoRoute: typeof RequerimentosNovoRoute
  VTokenRoute: typeof VTokenRoute
  DenunciasIndexRoute: typeof DenunciasIndexRoute
  EmpreendimentosIndexRoute: typeof EmpreendimentosIndexRoute
  EmpresasIndexRoute: typeof EmpresasIndexRoute
  RequerimentosIndexRoute: typeof RequerimentosIndexRoute
  DenunciasIdEditarRoute: typeof DenunciasIdEditarRoute
  EmpreendimentosIdEditarRoute: typeof EmpreendimentosIdEditarRoute
  EmpresasIdEditarRoute: typeof EmpresasIdEditarRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicV1EmpreendimentosRoute: typeof ApiPublicV1EmpreendimentosRoute
  ApiPublicV1EmpresasRoute: typeof ApiPublicV1EmpresasRoute
  ApiPublicV1OpenapiRoute: typeof ApiPublicV1OpenapiRoute
  ApiPublicV1RequerimentosRoute: typeof ApiPublicV1RequerimentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim': {
      id: '/sim'
      path: '/sim'
      fullPath: '/sim'
      preLoaderRoute: typeof SimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reurb': {
      id: '/reurb'
      path: '/reurb'
      fullPath: '/reurb'
      preLoaderRoute: typeof ReurbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-admin': {
      id: '/painel-admin'
      path: '/painel-admin'
      fullPath: '/painel-admin'
      preLoaderRoute: typeof PainelAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscalizacao': {
      id: '/fiscalizacao'
      path: '/fiscalizacao'
      fullPath: '/fiscalizacao'
      preLoaderRoute: typeof FiscalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta-publica': {
      id: '/consulta-publica'
      path: '/consulta-publica'
      fullPath: '/consulta-publica'
      preLoaderRoute: typeof ConsultaPublicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concluir-cadastro': {
      id: '/concluir-cadastro'
      path: '/concluir-cadastro'
      fullPath: '/concluir-cadastro'
      preLoaderRoute: typeof ConcluirCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ater': {
      id: '/ater'
      path: '/ater'
      fullPath: '/ater'
      preLoaderRoute: typeof AterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requerimentos/': {
      id: '/requerimentos/'
      path: '/requerimentos'
      fullPath: '/requerimentos/'
      preLoaderRoute: typeof RequerimentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/': {
      id: '/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof EmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/': {
      id: '/empreendimentos/'
      path: '/empreendimentos'
      fullPath: '/empreendimentos/'
      preLoaderRoute: typeof EmpreendimentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncias/': {
      id: '/denuncias/'
      path: '/denuncias'
      fullPath: '/denuncias/'
      preLoaderRoute: typeof DenunciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requerimentos/novo': {
      id: '/requerimentos/novo'
      path: '/requerimentos/novo'
      fullPath: '/requerimentos/novo'
      preLoaderRoute: typeof RequerimentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requerimentos/$id': {
      id: '/requerimentos/$id'
      path: '/requerimentos/$id'
      fullPath: '/requerimentos/$id'
      preLoaderRoute: typeof RequerimentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/modulos': {
      id: '/host/modulos'
      path: '/modulos'
      fullPath: '/host/modulos'
      preLoaderRoute: typeof HostModulosRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/api-docs': {
      id: '/host/api-docs'
      path: '/api-docs'
      fullPath: '/host/api-docs'
      preLoaderRoute: typeof HostApiDocsRouteImport
      parentRoute: typeof HostRoute
    }
    '/empresas/nova': {
      id: '/empresas/nova'
      path: '/empresas/nova'
      fullPath: '/empresas/nova'
      preLoaderRoute: typeof EmpresasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/novo': {
      id: '/empreendimentos/novo'
      path: '/empreendimentos/novo'
      fullPath: '/empreendimentos/novo'
      preLoaderRoute: typeof EmpreendimentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/mapa': {
      id: '/empreendimentos/mapa'
      path: '/empreendimentos/mapa'
      fullPath: '/empreendimentos/mapa'
      preLoaderRoute: typeof EmpreendimentosMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos/emitidos': {
      id: '/documentos/emitidos'
      path: '/emitidos'
      fullPath: '/documentos/emitidos'
      preLoaderRoute: typeof DocumentosEmitidosRouteImport
      parentRoute: typeof DocumentosRoute
    }
    '/denuncias/nova': {
      id: '/denuncias/nova'
      path: '/denuncias/nova'
      fullPath: '/denuncias/nova'
      preLoaderRoute: typeof DenunciasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tipos-requerimento': {
      id: '/admin/tipos-requerimento'
      path: '/admin/tipos-requerimento'
      fullPath: '/admin/tipos-requerimento'
      preLoaderRoute: typeof AdminTiposRequerimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pdf-templates': {
      id: '/admin/pdf-templates'
      path: '/admin/pdf-templates'
      fullPath: '/admin/pdf-templates'
      preLoaderRoute: typeof AdminPdfTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/papel': {
      id: '/admin/papel'
      path: '/admin/papel'
      fullPath: '/admin/papel'
      preLoaderRoute: typeof AdminPapelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/admin/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cepram': {
      id: '/admin/cepram'
      path: '/admin/cepram'
      fullPath: '/admin/cepram'
      preLoaderRoute: typeof AdminCepramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api-tokens': {
      id: '/admin/api-tokens'
      path: '/admin/api-tokens'
      fullPath: '/admin/api-tokens'
      preLoaderRoute: typeof AdminApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requerimentos/$id/editar': {
      id: '/requerimentos/$id/editar'
      path: '/editar'
      fullPath: '/requerimentos/$id/editar'
      preLoaderRoute: typeof RequerimentosIdEditarRouteImport
      parentRoute: typeof RequerimentosIdRoute
    }
    '/empresas/$id/editar': {
      id: '/empresas/$id/editar'
      path: '/empresas/$id/editar'
      fullPath: '/empresas/$id/editar'
      preLoaderRoute: typeof EmpresasIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/$id/editar': {
      id: '/empreendimentos/$id/editar'
      path: '/empreendimentos/$id/editar'
      fullPath: '/empreendimentos/$id/editar'
      preLoaderRoute: typeof EmpreendimentosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncias/$id/editar': {
      id: '/denuncias/$id/editar'
      path: '/denuncias/$id/editar'
      fullPath: '/denuncias/$id/editar'
      preLoaderRoute: typeof DenunciasIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios/novo': {
      id: '/admin/usuarios/novo'
      path: '/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AdminUsuariosNovoRouteImport
      parentRoute: typeof AdminUsuariosRoute
    }
    '/api/public/v1/requerimentos': {
      id: '/api/public/v1/requerimentos'
      path: '/api/public/v1/requerimentos'
      fullPath: '/api/public/v1/requerimentos'
      preLoaderRoute: typeof ApiPublicV1RequerimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi': {
      id: '/api/public/v1/openapi'
      path: '/api/public/v1/openapi'
      fullPath: '/api/public/v1/openapi'
      preLoaderRoute: typeof ApiPublicV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/empresas': {
      id: '/api/public/v1/empresas'
      path: '/api/public/v1/empresas'
      fullPath: '/api/public/v1/empresas'
      preLoaderRoute: typeof ApiPublicV1EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/empreendimentos': {
      id: '/api/public/v1/empreendimentos'
      path: '/api/public/v1/empreendimentos'
      fullPath: '/api/public/v1/empreendimentos'
      preLoaderRoute: typeof ApiPublicV1EmpreendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocumentosRouteChildren {
  DocumentosEmitidosRoute: typeof DocumentosEmitidosRoute
}

const DocumentosRouteChildren: DocumentosRouteChildren = {
  DocumentosEmitidosRoute: DocumentosEmitidosRoute,
}

const DocumentosRouteWithChildren = DocumentosRoute._addFileChildren(
  DocumentosRouteChildren,
)

interface HostRouteChildren {
  HostApiDocsRoute: typeof HostApiDocsRoute
  HostModulosRoute: typeof HostModulosRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostApiDocsRoute: HostApiDocsRoute,
  HostModulosRoute: HostModulosRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

interface AdminUsuariosRouteChildren {
  AdminUsuariosNovoRoute: typeof AdminUsuariosNovoRoute
}

const AdminUsuariosRouteChildren: AdminUsuariosRouteChildren = {
  AdminUsuariosNovoRoute: AdminUsuariosNovoRoute,
}

const AdminUsuariosRouteWithChildren = AdminUsuariosRoute._addFileChildren(
  AdminUsuariosRouteChildren,
)

interface RequerimentosIdRouteChildren {
  RequerimentosIdEditarRoute: typeof RequerimentosIdEditarRoute
}

const RequerimentosIdRouteChildren: RequerimentosIdRouteChildren = {
  RequerimentosIdEditarRoute: RequerimentosIdEditarRoute,
}

const RequerimentosIdRouteWithChildren = RequerimentosIdRoute._addFileChildren(
  RequerimentosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AterRoute: AterRoute,
  ConcluirCadastroRoute: ConcluirCadastroRoute,
  ConsultaPublicaRoute: ConsultaPublicaRoute,
  DocumentosRoute: DocumentosRouteWithChildren,
  FiscalizacaoRoute: FiscalizacaoRoute,
  GisRoute: GisRoute,
  HostRoute: HostRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificacoesRoute: NotificacoesRoute,
  PainelAdminRoute: PainelAdminRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReurbRoute: ReurbRoute,
  SimRoute: SimRoute,
  TermosRoute: TermosRoute,
  AdminApiTokensRoute: AdminApiTokensRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCepramRoute: AdminCepramRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPapelRoute: AdminPapelRoute,
  AdminPdfTemplatesRoute: AdminPdfTemplatesRoute,
  AdminTiposRequerimentoRoute: AdminTiposRequerimentoRoute,
  AdminUsuariosRoute: AdminUsuariosRouteWithChildren,
  DenunciasNovaRoute: DenunciasNovaRoute,
  EmpreendimentosMapaRoute: EmpreendimentosMapaRoute,
  EmpreendimentosNovoRoute: EmpreendimentosNovoRoute,
  EmpresasNovaRoute: EmpresasNovaRoute,
  RequerimentosIdRoute: RequerimentosIdRouteWithChildren,
  RequerimentosNovoRoute: RequerimentosNovoRoute,
  VTokenRoute: VTokenRoute,
  DenunciasIndexRoute: DenunciasIndexRoute,
  EmpreendimentosIndexRoute: EmpreendimentosIndexRoute,
  EmpresasIndexRoute: EmpresasIndexRoute,
  RequerimentosIndexRoute: RequerimentosIndexRoute,
  DenunciasIdEditarRoute: DenunciasIdEditarRoute,
  EmpreendimentosIdEditarRoute: EmpreendimentosIdEditarRoute,
  EmpresasIdEditarRoute: EmpresasIdEditarRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicV1EmpreendimentosRoute: ApiPublicV1EmpreendimentosRoute,
  ApiPublicV1EmpresasRoute: ApiPublicV1EmpresasRoute,
  ApiPublicV1OpenapiRoute: ApiPublicV1OpenapiRoute,
  ApiPublicV1RequerimentosRoute: ApiPublicV1RequerimentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
